create_clock -period 5.000 -name clk_in -waveform {0.000 2.500} [get_ports clk_in]

set_property PACKAGE_PIN C4 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]


set_property PACKAGE_PIN V11 [get_ports {rx_leds[7]}]
set_property PACKAGE_PIN V12 [get_ports {rx_leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {rx_leds[5]}]
set_property PACKAGE_PIN V15 [get_ports {rx_leds[4]}]
set_property PACKAGE_PIN T16 [get_ports {rx_leds[3]}]
set_property PACKAGE_PIN U14 [get_ports {rx_leds[2]}]
set_property PACKAGE_PIN T15 [get_ports {rx_leds[1]}]
set_property PACKAGE_PIN V16 [get_ports {rx_leds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {rx_leds[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property PACKAGE_PIN J15 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN V10 [get_ports {data[7]}]
set_property PACKAGE_PIN U11 [get_ports {data[6]}]
set_property PACKAGE_PIN U12 [get_ports {data[5]}]
set_property PACKAGE_PIN H6 [get_ports {data[4]}]
set_property PACKAGE_PIN T13 [get_ports {data[3]}]
set_property PACKAGE_PIN R16 [get_ports {data[2]}]
set_property PACKAGE_PIN U8 [get_ports {data[1]}]
set_property PACKAGE_PIN T8 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Tansmit_switch]
set_property IOSTANDARD LVCMOS33 [get_ports Transmit_btn]
set_property IOSTANDARD LVCMOS33 [get_ports TxD]
set_property PACKAGE_PIN L16 [get_ports Tansmit_switch]
set_property PACKAGE_PIN P18 [get_ports Transmit_btn]
set_property PACKAGE_PIN D4 [get_ports TxD]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_break]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_valid]
set_property PACKAGE_PIN H17 [get_ports uart_rx_break]
set_property PACKAGE_PIN K15 [get_ports uart_rx_valid]
