
set_property IOSTANDARD LVCMOS33 [get_ports {anode[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {ssd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk_Debug]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_Debug]
set_property IOSTANDARD LVCMOS33 [get_ports Transmit_btn]
set_property IOSTANDARD LVCMOS33 [get_ports Transmit_btn_Debug]
set_property IOSTANDARD LVCMOS33 [get_ports TxD]
set_property IOSTANDARD LVCMOS33 [get_ports TxD_Debug]
set_property PACKAGE_PIN U13 [get_ports {anode[7]}]

set_property PACKAGE_PIN K2 [get_ports {anode[6]}]
set_property PACKAGE_PIN T14 [get_ports {anode[5]}]
set_property PACKAGE_PIN P14 [get_ports {anode[4]}]
set_property PACKAGE_PIN J14 [get_ports {anode[3]}]
set_property PACKAGE_PIN T9 [get_ports {anode[2]}]
set_property PACKAGE_PIN J18 [get_ports {anode[1]}]
set_property PACKAGE_PIN J17 [get_ports {anode[0]}]

set_property PACKAGE_PIN H15 [get_ports {ssd[7]}]
set_property PACKAGE_PIN L18 [get_ports {ssd[6]}]
set_property PACKAGE_PIN T11 [get_ports {ssd[5]}]
set_property PACKAGE_PIN P15 [get_ports {ssd[4]}]
set_property PACKAGE_PIN K13 [get_ports {ssd[3]}]
set_property PACKAGE_PIN K16 [get_ports {ssd[2]}]
set_property PACKAGE_PIN R10 [get_ports {ssd[1]}]
set_property PACKAGE_PIN T10 [get_ports {ssd[0]}]

set_property PACKAGE_PIN V10 [get_ports {data[7]}]
set_property PACKAGE_PIN U11 [get_ports {data[6]}]
set_property PACKAGE_PIN U12 [get_ports {data[5]}]
set_property PACKAGE_PIN H6 [get_ports {data[4]}]
set_property PACKAGE_PIN T13 [get_ports {data[3]}]
set_property PACKAGE_PIN R16 [get_ports {data[2]}]
set_property PACKAGE_PIN U8 [get_ports {data[1]}]
set_property PACKAGE_PIN T8 [get_ports {data[0]}]

set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN V11 [get_ports clk_Debug]
set_property PACKAGE_PIN J15 [get_ports rst]
set_property PACKAGE_PIN H17 [get_ports rst_n_Debug]
set_property PACKAGE_PIN M18 [get_ports Transmit_btn]
set_property PACKAGE_PIN V12 [get_ports Transmit_btn_Debug]
set_property PACKAGE_PIN D4 [get_ports TxD]
set_property PACKAGE_PIN V14 [get_ports TxD_Debug]
